'use client';

import { useMemo, useState } from 'react';
import PortalHeader from '../portal-header';

const brl = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 });
const numero = (valor: unknown) => typeof valor === 'number' ? valor : Number(String(valor ?? '').replace(/\./g, '').replace(',', '.').replace(/[^\d.-]/g, '')) || 0;
const pegar = (registro: any, ...chaves: string[]) => chaves.map(chave => registro[chave]).find(valor => valor !== undefined && valor !== null && valor !== '');
const anoDe = (valor: unknown) => { const encontrado = String(valor ?? '').match(/20\d{2}|\d{2}(?=\D*$)/); return encontrado ? Number(encontrado[0].length === 2 ? '20' + encontrado[0] : encontrado[0]) : 0; };
const percentual = (valor: number, base: number) => base ? (valor / base * 100).toLocaleString('pt-BR', { maximumFractionDigits: 1 }) + '%' : '—';

export default function TurmasGanhas({ dados, email, sair }: { dados: any; email: string; sair: () => Promise<void> }) {
  const [periodo, setPeriodo] = useState('2026');
  const [busca, setBusca] = useState('');
  const turmas = useMemo(() => (dados.turmasGanhas || dados.turmas_ganhas || []).map((registro: any) => {
    const ganhou = pegar(registro, 'ganhou', 'GANHOU'); const fee = numero(pegar(registro, 'fee', 'FEE')); const beneficio = numero(pegar(registro, 'beneficio', 'BENEFÍCIO', 'BENEFICIOS')); const custo = numero(pegar(registro, 'custoComercial', 'CUSTO COMERCIAL')); const imposto = numero(pegar(registro, 'imposto', 'IMPOSTO')); const base = fee - beneficio - custo;
    return { job: String(pegar(registro, 'job', 'JOB') ?? '—'), turma: String(pegar(registro, 'turma', 'TURMA') ?? 'Sem identificação'), ganhou, ano: anoDe(ganhou), faturamento: numero(pegar(registro, 'faturamento', 'FATURAMENTO')), fee, imposto, beneficio, custo, base, comissaoTime: base * .10, comissaoLideranca: base * .02, margemFinal: base * .88 };
  }), [dados]);
  const filtradas = turmas.filter((turma: any) => (periodo === 'todos' || turma.ano === Number(periodo)) && `${turma.job} ${turma.turma}`.toLowerCase().includes(busca.toLowerCase()));
  const total = (campo: string, lista = filtradas) => lista.reduce((soma: number, turma: any) => soma + turma[campo], 0);
  const fee = total('fee'), imposto = total('imposto'), faturamento = total('faturamento'), custo = total('custo'), beneficios = total('beneficio'), base = total('base'), time = total('comissaoTime'), lideranca = total('comissaoLideranca'), margemFinal = total('margemFinal');
  const anoSelecionado = Number(periodo), meta = Number(dados.metasFee?.[anoSelecionado]?.meta || 0), over = Number(dados.metasFee?.[anoSelecionado]?.overMeta || 0), anterior = total('fee', turmas.filter((turma: any) => turma.ano === anoSelecionado - 1));
  const largura = (valor: number, referencia: number) => `${Math.min(referencia ? valor / referencia * 100 : 0, 100)}%`;
  return <main><PortalHeader titulo="Turmas ganhas" descricao="Faturamento, fee, meta e rentabilidade da carteira comercial." atual="turmas" email={email} sair={sair} />
    <section className="toolbar"><label>Período<select value={periodo} onChange={e => setPeriodo(e.target.value)}><option value="todos">Todos os anos</option><option value="2024">2024</option><option value="2025">2025</option><option value="2026">2026</option></select></label><label>Buscar turma ou job<input value={busca} onChange={e => setBusca(e.target.value)} placeholder="Ex.: EINSTEIN ou 27500377" /></label><span>{filtradas.length} turmas na visão</span><small>Atualizado: {dados.atualizadoEm}</small></section>
    {!turmas.length ? <section className="panel"><h2>Base aguardando integração</h2><p>A API ainda não retornou turmas ganhas.</p></section> : <><section className="cards"><Card t="FATURAMENTO PROJETADO" v={brl.format(faturamento)} d="Arrecadação total dos projetos" hot /><Card t="FEE CONTRATADO" v={brl.format(fee)} d={`${percentual(fee, faturamento)} do faturamento`} /><Card t="VALOR COBRADO DO CLIENTE" v={brl.format(fee + imposto)} d={`Fee + imposto de ${brl.format(imposto)}`} /><Card t="MARGEM FINAL DA EMPRESA" v={brl.format(margemFinal)} d="Após comissões de 10% + 2%" /></section>
    {periodo !== 'todos' && <section className="grid"><article><h2>Régua de meta comercial {periodo}</h2><p>Fee conquistado versus meta aprovada.</p><div className="goal"><div><span>Conquistado</span><b>{brl.format(fee)}</b></div><div className="goal-track"><i style={{ width: largura(fee, meta) }} /></div><div className="goal-labels"><span>{percentual(fee, meta)} da meta</span><span>Meta: {brl.format(meta)}</span></div><div className="goal-details"><span>Falta: <b>{brl.format(Math.max(meta - fee, 0))}</b></span>{over > 0 && <span>Over meta: <b>{brl.format(over)}</b> · faltam {brl.format(Math.max(over - fee, 0))}</span>}</div></div></article><article><h2>Comparativo anual</h2><dl><dt>Fee {anoSelecionado - 1}</dt><dd>{brl.format(anterior)}</dd><dt>Variação</dt><dd className={fee >= anterior ? 'ok' : 'risk'}>{percentual(fee - anterior, anterior)}</dd><dt>Base comissionável</dt><dd>{brl.format(base)}</dd><dt>Margem final / fee</dt><dd>{percentual(margemFinal, fee)}</dd></dl></article></section>}
    <section className="cards extra"><Card t="CUSTO DE AQUISIÇÃO" v={brl.format(custo)} d="Gasto realizado para ganhar a turma" /><Card t="BENEFÍCIOS COMPROMETIDOS" v={brl.format(beneficios)} d="Compromisso futuro do projeto" /><Card t="COMISSÕES (12%)" v={brl.format(time + lideranca)} d={`Time ${brl.format(time)} + liderança ${brl.format(lideranca)}`} /><Card t="TURMAS GANHAS" v={String(filtradas.length)} d="Carteira filtrada" /></section>
    <section className="panel"><h2>Carteira e rentabilidade por turma</h2><p>Base comissionável = Fee − benefícios − custo de aquisição. Imposto é cobrado à parte e não reduz o fee.</p><div className="table-wrap"><table><thead><tr><th>Job</th><th>Turma</th><th>Ganhou em</th><th style={{ textAlign: 'right' }}>Faturamento</th><th style={{ textAlign: 'right' }}>Fee</th><th style={{ textAlign: 'right' }}>Imposto</th><th style={{ textAlign: 'right' }}>Benefícios</th><th style={{ textAlign: 'right' }}>Custo de aquisição</th><th style={{ textAlign: 'right' }}>Comissão time</th><th style={{ textAlign: 'right' }}>Liderança</th><th style={{ textAlign: 'right' }}>Margem final</th><th style={{ textAlign: 'right' }}>Margem %</th></tr></thead><tbody>{[...filtradas].sort((a: any, b: any) => b.margemFinal - a.margemFinal).map((turma: any) => { const margem = turma.fee ? turma.margemFinal / turma.fee * 100 : 0; const cor = margem >= 80 ? '#087a53' : margem >= 50 ? '#b17700' : '#c84747'; return <tr key={turma.job + turma.turma}><td>{turma.job}</td><td>{turma.turma}</td><td>{turma.ganhou || '—'}</td><td style={{ textAlign: 'right' }}>{brl.format(turma.faturamento)}</td><td style={{ textAlign: 'right' }}>{brl.format(turma.fee)}</td><td style={{ textAlign: 'right' }}>{brl.format(turma.imposto)}</td><td style={{ textAlign: 'right' }}>{brl.format(turma.beneficio)}</td><td style={{ textAlign: 'right' }}>{brl.format(turma.custo)}</td><td style={{ textAlign: 'right' }}>{brl.format(turma.comissaoTime)}</td><td style={{ textAlign: 'right' }}>{brl.format(turma.comissaoLideranca)}</td><td style={{ textAlign: 'right' }}><b>{brl.format(turma.margemFinal)}</b></td><td style={{ textAlign: 'right' }}><span style={{ display: 'inline-block', minWidth: 44, color: cor, fontWeight: 700 }}>{percentual(turma.margemFinal, turma.fee)}</span><i style={{ display: 'inline-block', width: 54, height: 6, marginLeft: 7, verticalAlign: 'middle', borderRadius: 99, background: `linear-gradient(90deg, ${cor} ${Math.max(0, Math.min(margem, 100))}%, #ece7ef ${Math.max(0, Math.min(margem, 100))}%)` }} /></td></tr>; })}</tbody><tfoot><tr><th colSpan={3}>Total</th><th style={{ textAlign: 'right' }}>{brl.format(faturamento)}</th><th style={{ textAlign: 'right' }}>{brl.format(fee)}</th><th style={{ textAlign: 'right' }}>{brl.format(imposto)}</th><th style={{ textAlign: 'right' }}>{brl.format(beneficios)}</th><th style={{ textAlign: 'right' }}>{brl.format(custo)}</th><th style={{ textAlign: 'right' }}>{brl.format(time)}</th><th style={{ textAlign: 'right' }}>{brl.format(lideranca)}</th><th style={{ textAlign: 'right' }}>{brl.format(margemFinal)}</th><th style={{ textAlign: 'right' }}>{percentual(margemFinal, fee)}</th></tr></tfoot></table></div></section></>}</main>;
}

function Card({ t, v, d, hot }: { t: string; v: string; d: string; hot?: boolean }) { return <article className={hot ? 'hot' : ''}><small>{t}</small><strong>{v}</strong><span>{d}</span></article>; }
