'use client';

import { useMemo, useState } from 'react';
import PortalHeader from '../portal-header';

const brl = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 });
const nomesMeses = ['', 'janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro'];
const numero = (v: unknown) => typeof v === 'number' ? v : Number(String(v ?? '').replace(/\./g, '').replace(',', '.').replace(/[^\d.-]/g, '')) || 0;
const pegar = (r: any, ...chaves: string[]) => chaves.map(chave => r[chave]).find(valor => valor !== undefined && valor !== null && valor !== '');
const percentual = (v: number, b: number) => b ? `${(v / b * 100).toLocaleString('pt-BR', { maximumFractionDigits: 1 })}%` : '—';
const anoDe = (v: unknown) => { const m = String(v ?? '').match(/20\d{2}|\d{2}(?=\D*$)/); return m ? Number(m[0].length === 2 ? `20${m[0]}` : m[0]) : 0; };
const mesDe = (v: unknown) => { const meses: Record<string, number> = { jan: 1, fev: 2, mar: 3, abr: 4, mai: 5, jun: 6, jul: 7, ago: 8, set: 9, out: 10, nov: 11, dez: 12 }; const m = String(v ?? '').toLowerCase().replace('.', '').match(/(jan|fev|mar|abr|mai|jun|jul|ago|set|out|nov|dez)/); return m ? meses[m[1]] : 0; };
const prazoEmMeses = (inicio?: string, fim?: string) => { const nomes: Record<string, number> = { jan: 0, fev: 1, mar: 2, abr: 3, mai: 4, jun: 5, jul: 6, ago: 7, set: 8, out: 9, nov: 10, dez: 11 }; const ler = (v?: string) => { const m = String(v || '').toLowerCase().replace('.', '').match(/(jan|fev|mar|abr|mai|jun|jul|ago|set|out|nov|dez)[/\s-]*(\d{2,4})/); return m ? { mes: nomes[m[1]], ano: Number(m[2].length === 2 ? `20${m[2]}` : m[2]) } : null; }; const a = ler(inicio), b = ler(fim); return a && b ? Math.max(0, (b.ano - a.ano) * 12 + b.mes - a.mes + 1) : null; };

function Card({ titulo, valor, descricao, destaque }: { titulo: string; valor: string; descricao: string; destaque?: boolean }) { return <article className={destaque ? 'hot' : ''}><small>{titulo}</small><strong>{valor}</strong><span>{descricao}</span></article>; }

export default function TurmasGanhas({ dados, email, sair }: { dados: any; email: string; sair: () => Promise<void> }) {
  const [periodo, setPeriodo] = useState('2026');
  const [empresa, setEmpresa] = useState('TODAS');
  const [busca, setBusca] = useState('');
  const [detalhes, setDetalhes] = useState(false);
  const [ordem, setOrdem] = useState({ campo: 'margemFinal', direcao: 'desc' as 'asc' | 'desc' });
  const referencia = String(dados.projecaoEntradas?.mensal?.[0]?.competencia || '');
  const mesReferencia = Number(referencia.slice(5, 7)) || 0;

  const turmas = useMemo(() => (dados.turmasGanhas || dados.turmas_ganhas || []).map((registro: any) => {
    const ganhou = pegar(registro, 'ganhou', 'GANHOU'), fee = numero(pegar(registro, 'fee', 'FEE')), beneficio = numero(pegar(registro, 'beneficio', 'BENEFÍCIO', 'BENEFICIOS')), custo = numero(pegar(registro, 'custoComercial', 'CUSTO COMERCIAL')), imposto = numero(pegar(registro, 'imposto', 'IMPOSTO')), contrato = registro.contrato || {};
    const base = fee - beneficio - custo;
    return { job: String(pegar(registro, 'job', 'JOB') ?? '—'), empresa: String(pegar(registro, 'empresa', 'cluster', 'CLUSTER') || '').toUpperCase(), turma: String(pegar(registro, 'turma', 'TURMA') ?? 'Sem identificação'), ganhou, ano: anoDe(ganhou), mes: mesDe(ganhou), faturamento: numero(pegar(registro, 'faturamento', 'FATURAMENTO')), fee, imposto, beneficio, custo, base, comissaoTime: base * .10, comissaoLideranca: base * .02, margemFinal: base * .88, margemPct: fee ? base * .88 / fee : 0, temContrato: Boolean(registro.temContrato || contrato.status === 'ASSINADO'), inicioFee: contrato.inicioFee || '', fimFee: contrato.fimFee || '', prazoFee: prazoEmMeses(contrato.inicioFee, contrato.fimFee) };
  }), [dados]);

  const filtradas = turmas.filter((turma: any) => (periodo === 'todos' || turma.ano === Number(periodo)) && (empresa === 'TODAS' || turma.empresa === empresa) && `${turma.job} ${turma.turma}`.toLowerCase().includes(busca.toLowerCase()));
  const total = (campo: string, lista: any[] = filtradas) => lista.reduce((soma: number, turma: any) => soma + turma[campo], 0);
  const fee = total('fee'), imposto = total('imposto'), faturamento = total('faturamento'), custo = total('custo'), beneficios = total('beneficio'), base = total('base'), time = total('comissaoTime'), lideranca = total('comissaoLideranca'), margemFinal = total('margemFinal');
  const ano = Number(periodo), meta = Number(dados.metasFee?.[ano]?.meta || 0), over = Number(dados.metasFee?.[ano]?.overMeta || 0);
  const comparavelAnterior = turmas.filter((turma: any) => turma.ano === ano - 1 && (!mesReferencia || turma.mes <= mesReferencia));
  const anterior = total('fee', comparavelAnterior);
  const mesesCompletos = mesReferencia ? Math.max(1, mesReferencia - 1) : 0;
  const fechamento = periodo !== 'todos' && mesesCompletos ? fee / mesesCompletos * 12 : 0;
  const prazos = filtradas.map((turma: any) => turma.prazoFee).filter((prazo: any) => prazo !== null);
  const prazoMedio = prazos.length ? prazos.reduce((soma: number, prazo: number) => soma + prazo, 0) / prazos.length : 0;
  const ordenar = (campo: string) => setOrdem(atual => ({ campo, direcao: atual.campo === campo && atual.direcao === 'desc' ? 'asc' : 'desc' }));
  const linhas = [...filtradas].sort((a: any, b: any) => { const av = a[ordem.campo], bv = b[ordem.campo], r = typeof av === 'number' ? av - bv : String(av ?? '').localeCompare(String(bv ?? ''), 'pt-BR', { numeric: true }); return ordem.direcao === 'asc' ? r : -r; });
  const H = ({ campo, children, num }: { campo: string; children: React.ReactNode; num?: boolean }) => <th style={{ textAlign: num ? 'right' : 'left' }}><button type="button" style={{ appearance: 'none', border: 0, background: 'transparent', padding: 0, color: 'inherit', font: 'inherit', letterSpacing: 'inherit', textTransform: 'inherit', cursor: 'pointer', opacity: .78 }} onClick={() => ordenar(campo)}>{children} {ordem.campo === campo ? (ordem.direcao === 'asc' ? '↑' : '↓') : '↕'}</button></th>;
  const faixa = (v: number) => v >= .7 ? { cor: '#087a53', fundo: '#e4f7ed' } : v >= .5 ? { cor: '#9a6700', fundo: '#fff4cc' } : { cor: '#c84747', fundo: '#fdeaea' };

  return <main>
    <PortalHeader titulo="Turmas ganhas" descricao="Faturamento, Fee, meta e rentabilidade da carteira comercial." atual="turmas" email={email} sair={sair} referencia={periodo === 'todos' ? 'Carteira consolidada' : `Ano comercial ${periodo}`} atualizadoEm={dados.atualizadoEm} />
    <section className="toolbar"><label>Período<select value={periodo} onChange={e => setPeriodo(e.target.value)}><option value="todos">Todos os anos</option><option value="2024">2024</option><option value="2025">2025</option><option value="2026">2026</option></select></label><label>Empresa<select value={empresa} onChange={e => setEmpresa(e.target.value)}><option value="TODAS">Consolidado</option><option value="FORMA">FORMA</option><option value="MED">MED</option></select></label><label>Buscar turma ou Job<input value={busca} onChange={e => setBusca(e.target.value)} placeholder="Ex.: EINSTEIN ou 27500377" /></label><span>{filtradas.length} turmas na visão</span></section>
    <section className="cards"><Card titulo="FEE CONTRATADO" valor={brl.format(fee)} descricao={meta ? `${percentual(fee, meta)} da meta anual` : 'Meta não definida'} destaque /><Card titulo="MARGEM FINAL" valor={brl.format(margemFinal)} descricao={`${percentual(margemFinal, fee)} do Fee contratado`} destaque /><Card titulo="FATURAMENTO PROJETADO" valor={brl.format(faturamento)} descricao="Arrecadação total dos projetos" /><Card titulo="TICKET MÉDIO DE FEE" valor={brl.format(filtradas.length ? fee / filtradas.length : 0)} descricao="Por turma da visão selecionada" /></section>
    <section className="cards extra"><Card titulo="PRAZO MÉDIO DE FEE" valor={prazoMedio ? `${prazoMedio.toFixed(0)} meses` : '—'} descricao="Somente contratos identificados" /><Card titulo="CUSTO DE AQUISIÇÃO" valor={brl.format(custo)} descricao="Gasto realizado para ganhar a turma" /><Card titulo="BENEFÍCIOS COMPROMETIDOS" valor={brl.format(beneficios)} descricao="Compromisso futuro dos projetos" /><Card titulo="COMISSÕES (12%)" valor={brl.format(time + lideranca)} descricao="10% time comercial + 2% liderança" /></section>
    {periodo !== 'todos' && <section className="grid"><article><h2>Régua de meta comercial {periodo}</h2><p>Fee conquistado versus meta aprovada.</p><div className="goal"><div><span>Conquistado</span><b>{brl.format(fee)}</b></div><div className="goal-track"><i style={{ width: `${Math.min(meta ? fee / meta * 100 : 0, 100)}%` }} /></div><div className="goal-labels"><span>{percentual(fee, meta)} da meta</span><span>Meta: {brl.format(meta)}</span></div><div className="goal-details"><span>Falta: <b>{brl.format(Math.max(meta - fee, 0))}</b></span>{over > 0 && <span>Over meta: <b>{brl.format(over)}</b> · faltam {brl.format(Math.max(over - fee, 0))}</span>}</div></div></article><article><h2>Comparativo anual</h2><dl><dt>Fee {ano - 1}{mesReferencia ? ` · até ${nomesMeses[mesReferencia]}` : ''}</dt><dd>{brl.format(anterior)}</dd><dt>Variação comparável</dt><dd className={fee >= anterior ? 'ok' : 'risk'}>{percentual(fee - anterior, anterior)}</dd><dt>Base comissionável</dt><dd>{brl.format(base)}</dd><dt>Margem final / Fee</dt><dd>{percentual(margemFinal, fee)}</dd></dl></article></section>}
    {fechamento > 0 && <section className="panel" style={{ background: '#281032', color: '#fff' }}><small style={{ color: '#d9c8e0' }}>PROJEÇÃO DE FECHAMENTO ANUAL</small><h2 style={{ marginTop: 5 }}>No ritmo atual, {periodo} encerra em {brl.format(fechamento)} de Fee.</h2><p style={{ color: '#d9c8e0' }}>Cálculo anualizado com base em {mesesCompletos} meses completos.</p></section>}
    <section className="panel"><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center' }}><div><h2>Carteira e rentabilidade por turma</h2><p>Margem / Fee: verde ≥ 70%, amarelo entre 50% e 69,9%, vermelho abaixo de 50%.</p></div><button type="button" onClick={() => setDetalhes(!detalhes)} style={{ border: '1px solid #d7cce0', borderRadius: 8, background: '#fff', padding: '8px 10px', cursor: 'pointer' }}>{detalhes ? 'Ocultar detalhes' : 'Ver mais colunas'}</button></div><div className="table-wrap"><table><thead><tr><H campo="empresa">Empresa</H><H campo="turma">Turma</H><H campo="ganhou">Ganhou em</H><H campo="fee" num>Fee</H><H campo="prazoFee" num>Prazo Fee</H><H campo="beneficio" num>Benefícios</H><H campo="custo" num>Custo aquisição</H><H campo="margemFinal" num>Margem final</H><H campo="margemPct" num>Margem / Fee</H>{detalhes && <><H campo="job">Job</H><H campo="faturamento" num>Faturamento</H><H campo="imposto" num>Imposto</H><H campo="comissaoTime" num>Comissão time</H><H campo="comissaoLideranca" num>Liderança</H></>}</tr></thead><tbody>{linhas.map((t: any) => { const cor = faixa(t.margemPct); return <tr key={t.job + t.turma}><td>{t.empresa || '—'}</td><td>{t.turma}</td><td>{t.ganhou || '—'}</td><td style={{ textAlign: 'right' }}>{brl.format(t.fee)}</td><td style={{ textAlign: 'right' }}>{t.prazoFee ? `${t.prazoFee} meses` : '—'}</td><td style={{ textAlign: 'right' }}>{brl.format(t.beneficio)}</td><td style={{ textAlign: 'right' }}>{brl.format(t.custo)}</td><td style={{ textAlign: 'right' }}><b>{brl.format(t.margemFinal)}</b></td><td style={{ textAlign: 'right' }}><b style={{ display: 'inline-block', minWidth: 48, padding: '3px 7px', borderRadius: 999, color: cor.cor, background: cor.fundo }}>{percentual(t.margemFinal, t.fee)}</b></td>{detalhes && <><td>{t.job}</td><td style={{ textAlign: 'right' }}>{brl.format(t.faturamento)}</td><td style={{ textAlign: 'right' }}>{brl.format(t.imposto)}</td><td style={{ textAlign: 'right' }}>{brl.format(t.comissaoTime)}</td><td style={{ textAlign: 'right' }}>{brl.format(t.comissaoLideranca)}</td></>}</tr>; })}</tbody><tfoot><tr><th colSpan={3}>Total</th><th style={{ textAlign: 'right' }}>{brl.format(fee)}</th><th>—</th><th style={{ textAlign: 'right' }}>{brl.format(beneficios)}</th><th style={{ textAlign: 'right' }}>{brl.format(custo)}</th><th style={{ textAlign: 'right' }}>{brl.format(margemFinal)}</th><th style={{ textAlign: 'right' }}>{percentual(margemFinal, fee)}</th>{detalhes && <><th>—</th><th style={{ textAlign: 'right' }}>{brl.format(faturamento)}</th><th style={{ textAlign: 'right' }}>{brl.format(imposto)}</th><th style={{ textAlign: 'right' }}>{brl.format(time)}</th><th style={{ textAlign: 'right' }}>{brl.format(lideranca)}</th></>}</tr></tfoot></table></div></section>
  </main>;
}
