'use client';
import { useMemo, useState } from 'react';
import PortalHeader from '../portal-header';

const brl = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 });
const num = (v: any) => typeof v === 'number' ? v : Number(String(v ?? '').replace(/\./g, '').replace(',', '.').replace(/[^\d.-]/g, '')) || 0;
const pick = (r: any, ...keys: string[]) => keys.map(k => r[k]).find(v => v !== undefined && v !== null && v !== '');
const yearOf = (v: any) => { const found = String(v ?? '').match(/20\d{2}|\d{2}(?=\D*$)/); return found ? Number(found[0].length === 2 ? `20${found[0]}` : found[0]) : 0; };
const pc = (v: number, base: number) => base ? `${(v / base * 100).toLocaleString('pt-BR', { maximumFractionDigits: 1 })}%` : '—';

export default function ResumoExecutivo({ dados, email, sair }: { dados: any; email: string; sair: () => Promise<void> }) {
  const [ano, setAno] = useState('2026');
  const carteira = useMemo(() => (dados.turmasGanhas || []).map((r: any) => {
    const fee = num(pick(r, 'fee', 'FEE')), beneficio = num(pick(r, 'beneficio', 'BENEFÍCIO')), custo = num(pick(r, 'custoComercial', 'CUSTO COMERCIAL')), ganhou = pick(r, 'ganhou', 'GANHOU');
    return { job: String(pick(r, 'job', 'JOB') || '—'), turma: String(pick(r, 'turma', 'TURMA') || 'Sem identificação'), ganhou, ano: yearOf(ganhou), faturamento: num(pick(r, 'faturamento', 'FATURAMENTO')), fee, beneficio, custo, margem: fee - beneficio - custo };
  }), [dados]);
  const linhas = carteira.filter((t: any) => ano === 'todos' || t.ano === Number(ano));
  const soma = (campo: 'faturamento' | 'fee' | 'beneficio' | 'custo' | 'margem', lista = linhas) => lista.reduce((s: number, t: any) => s + t[campo], 0);
  const fee = soma('fee'), margem = soma('margem'), investimento = soma('beneficio') + soma('custo'), meta = Number(dados.metasFee?.[Number(ano)]?.meta || 0);
  const top5 = [...linhas].sort((a: any, b: any) => b.fee - a.fee).slice(0, 5), concentracao = soma('fee', top5);
  const semFaturamento = linhas.filter((t: any) => !t.faturamento).length, semData = linhas.filter((t: any) => !t.ano).length, margemNegativa = linhas.filter((t: any) => t.margem < 0).length;
  const maior = Math.max(1, ...top5.map((t: any) => t.fee));
  return <main><PortalHeader titulo="Resumo executivo" descricao="Crescimento, qualidade da carteira e principais riscos comerciais." atual="executivo" email={email} sair={sair}/><section className="toolbar"><label>Competência comercial<select value={ano} onChange={e => setAno(e.target.value)}><option value="todos">Todos os anos</option><option value="2024">2024</option><option value="2025">2025</option><option value="2026">2026</option></select></label><span>{linhas.length} turmas na carteira</span><small>Dados comerciais atualizados: {dados.atualizadoEm}</small></section><section className="cards"><Card t="FEE CONTRATADO" v={brl.format(fee)} d={meta ? `${pc(fee, meta)} da meta anual` : 'Meta não definida para o período'} hot/><Card t="MARGEM COMERCIAL" v={brl.format(margem)} d={`${pc(margem, fee)} do fee, antes de comissão`} /><Card t="INVESTIMENTO COMERCIAL" v={brl.format(investimento)} d={`${pc(investimento, fee)} do fee contratado`} /><Card t="ARRECADAÇÃO DOS PROJETOS" v={brl.format(soma('faturamento'))} d="Potencial bruto das turmas" /></section><section className="grid"><article><h2>Concentração de fee</h2><p>As cinco maiores turmas representam {pc(concentracao, fee)} do fee da carteira. Concentração alta aumenta o risco de execução.</p><div className="fee-bars">{top5.map((t: any) => <div className="fee-bar" key={t.job}><i style={{ height: `${t.fee / maior * 165}px` }} /><small>{t.turma.slice(0, 14)}</small></div>)}</div></article><article><h2>Qualidade e riscos</h2><p>Itens que exigem acompanhamento.</p><dl><dt>Sem faturamento informado</dt><dd className={semFaturamento ? 'risk' : 'ok'}>{semFaturamento}</dd><dt>Sem data de ganho</dt><dd className={semData ? 'risk' : 'ok'}>{semData}</dd><dt>Margem comercial negativa</dt><dd className={margemNegativa ? 'risk' : 'ok'}>{margemNegativa}</dd><dt>Contratos ainda sem status</dt><dd className="risk">Não informado</dd></dl></article></section><section className="panel"><h2>Prioridades da carteira</h2><p>Turmas de maior contribuição. A margem é anterior à comissão e aos custos operacionais do projeto.</p><div className="table-wrap"><table><thead><tr><th>Job</th><th>Turma</th><th>Ganho em</th><th>Fee</th><th>Investimento comercial</th><th>Margem comercial</th><th>Margem %</th></tr></thead><tbody>{[...linhas].sort((a: any, b: any) => b.margem - a.margem).slice(0, 12).map((t: any) => <tr key={t.job}><td>{t.job}</td><td>{t.turma}</td><td>{t.ganhou || '—'}</td><td>{brl.format(t.fee)}</td><td>{brl.format(t.beneficio + t.custo)}</td><td><b>{brl.format(t.margem)}</b></td><td className={t.margem < 0 ? 'risk' : ''}>{pc(t.margem, t.fee)}</td></tr>)}</tbody></table></div></section><section className="panel"><h2>Nota de governança</h2><p>Fee está tratado como valor comercial contratado. Para a visão completa de CFO, as próximas integrações adicionarão contrato assinado, cronograma de recebimento, comissão provisionada e custo operacional.</p></section></main>;
}
function Card({ t, v, d, hot }: { t: string; v: string; d: string; hot?: boolean }) { return <article className={hot ? 'hot' : ''}><small>{t}</small><strong>{v}</strong><span>{d}</span></article>; }
